name: Create DB2 Change

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Ambiente (DEV/HML/PRD)"
        required: true
        default: "DEV"

      system_code:
        description: "Código do sistema (3 letras)"
        required: true

      table_name:
        description: "Nome da tabela"
        required: true

      user_id:
        description: "User mainframe (ex: A170580)"
        required: true

      ddl_sql:
        description: "Cole o DDL completo"
        required: true

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Criar estrutura
        run: |
          DATE=$(date +%Y-%m-%d)
          DIR="executions/${{ github.event.inputs.environment }}/$DATE"_create_"${{ github.event.inputs.table_name }}"

          mkdir -p $DIR/generated
          mkdir -p $DIR/logs

          echo "DIR=$DIR" >> $GITHUB_ENV

      - name: Salvar YAML
        run: |
          DIR=$(ls -d executions/*/* | tail -1)

          echo "change:" > $DIR/input.yml
          echo "  id: CHG-$(date +%Y%m%d)" >> $DIR/input.yml
          echo "  environment: ${{ github.event.inputs.environment }}" >> $DIR/input.yml

          echo "mainframe:" >> $DIR/input.yml
          echo "  user_id: ${{ github.event.inputs.user_id }}" >> $DIR/input.yml
          echo "  subsystem: DB2P" >> $DIR/input.yml

          echo "object:" >> $DIR/input.yml
          echo "  system_code: ${{ github.event.inputs.system_code }}" >> $DIR/input.yml
          echo "  table_name: ${{ github.event.inputs.table_name }}" >> $DIR/input.yml

          echo "ddl:" >> $DIR/input.yml
          echo "  sql: |" >> $DIR/input.yml

          while IFS= read -r line; do
            echo "    $line" >> $DIR/input.yml
          done <<< "${{ github.event.inputs.ddl_sql }}"

      - name: Gerar JCL
        run: |
          MAIN=$(cat templates/main.jcl)
          BIND=$(cat templates/bind.jclpart)
          REBUILD=$(cat templates/rebuild.jclpart)
          DECLGEN=$(cat templates/declare_gen.jclpart)

          MAIN=${MAIN//\{\{USER_ID\}\}/${{ github.event.inputs.user_id }}}
          MAIN=${MAIN//\{\{DB2_SUBSYSTEM\}\}/DB2P}
          MAIN=${MAIN//\{\{RUNLIB\}\}/DSN!!0.RUNLIB.LOAD}
          MAIN=${MAIN//\{\{SYSTEM_CODE\}\}/${{ github.event.inputs.system_code }}}
          MAIN=${MAIN//\{\{TABLE_NAME\}\}/${{ github.event.inputs.table_name }}}

          MAIN=${MAIN//\{\{DDL_SQL\}\}/${{ github.event.inputs.ddl_sql }}}
          MAIN=${MAIN//\{\{BIND_STEP\}\}/$BIND}
          MAIN=${MAIN//\{\{REBUILD_STEP\}\}/$REBUILD}
          MAIN=${MAIN//\{\{DECLGEN_STEP\}\}/$DECLGEN}

          echo "$MAIN" > $DIR/generated/final.jcl

      - name: Upload artefato
        uses: actions/upload-artifact@v5
        with:
          name: jcl-gerado
          path: executions/

#      - name: Commit automático
#        run: |
#          git config user.name "github-actions"
#          git config user.email "actions@github.com"
#          git add executions/
#          git commit -m "Nova mudança DB2"
#          git push
